//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string nombreEmpleado { get; set; }
        public string correoEmpleado { get; set; }
        public int numeroCelular { get; set; }
        public string rol { get; set; }
    }
}
